"""The one place every puzzle's authored data lives: `puzzles/catalog.json`.

A puzzle directory holds four kinds of file, and until this module existed
they were not distinguishable by looking at them:

    design.gds      authored (or generated from RTL by `gdsx puzzle build`)
    manifest.json   \\_ authored... in six directories, and generated from
    solution.json   /  Python literals in `scripts/build_puzzle.py` for the
                       seventh, which meant two spellings of the same prose
    netlist.json    generated by `gdsx puzzle bake`
    render.bin      generated by `gdsx puzzle bake`
    tape.bin        generated by `gdsx puzzle bake`
    hints.json      generated by `gdsx puzzle bake`

`manifest.json` and `solution.json` now join the generated half. Both are
written by `sync()` from `puzzles/catalog.json`, which carries every level's
title, difficulty, blurb, backstory, par, enabled tools, answer key and
verifier spec, in catalog order, in one file. Editing a level means editing
that file and re-running `gdsx puzzle sync`; editing a generated
`manifest.json` directly is a change that the next sync silently reverts, so
`tests/test_catalog.py` fails on any drift between the two.

**This module does not know what a puzzle means.** It is a router: each
entry's `manifest` and `solution` blocks are carried through verbatim, with
only the fields that are the same for every level (`schema_version`, `author`,
and the `id`, which is the entry's own key) filled in. That is deliberate --
`solution.json` is genuinely heterogeneous across the pack (a serial key here,
parallel tracks there, named parameter fields, a declared answer with no
simulation at all, three different schema versions still in use), and a
catalog that tried to normalise all of it would be a second, lossier
description of a format `puzzle.py` already documents in full.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

CATALOG = "catalog.json"
MANIFEST = "manifest.json"
SOLUTION = "solution.json"

#: Written into every generated `manifest.json`. `solution.json` keeps its own
#: per-puzzle `schema_version` -- versions 1, 2 and 3 are all still in use and
#: all still read (see `puzzle.py`), so it is authored data, not a constant.
MANIFEST_SCHEMA_VERSION = 1

#: Key order for a generated `manifest.json`. Fixed here so the files are
#: uniform and their diffs stay small; a key the catalog carries that is not
#: in this list is appended in catalog order rather than dropped.
_MANIFEST_ORDER = (
    "schema_version",
    "id",
    "title",
    "difficulty",
    "blurb",
    "backstory",
    "author",
    "answer_kind",
    "tools_enabled",
    "par_seconds",
    "guide",
)


class CatalogError(RuntimeError):
    """`puzzles/catalog.json` is missing, malformed, or disagrees with disk"""


@dataclass(frozen=True)
class Entry:
    """One level's authored data, as the catalog carries it."""

    id: str
    manifest: dict
    solution: dict


def load(puzzles_dir: Path) -> list[Entry]:
    """Every entry in `<puzzles_dir>/catalog.json`, in catalog order.

    Catalog order is the order levels are offered in, so it is preserved
    rather than sorted -- `web/scripts/puzzle-index.mjs` reads the directories
    and sorts by name, but that is its own concern.
    """
    path = puzzles_dir / CATALOG
    if not path.exists():
        raise CatalogError(f"{path}: no catalog to read")
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise CatalogError(f"{path}: not valid JSON -- {exc}") from None

    entries = data.get("puzzles")
    if not isinstance(entries, list) or not entries:
        raise CatalogError(f"{path}: lists no puzzles")

    author = data.get("author")
    out: list[Entry] = []
    seen: set[str] = set()
    for raw in entries:
        puzzle_id = raw.get("id")
        if not puzzle_id:
            raise CatalogError(f"{path}: an entry has no id")
        if puzzle_id in seen:
            raise CatalogError(f"{path}: {puzzle_id} appears twice")
        seen.add(puzzle_id)
        for block in ("manifest", "solution"):
            if not isinstance(raw.get(block), dict):
                raise CatalogError(f"{path}: {puzzle_id} has no {block} block")
        out.append(
            Entry(
                id=puzzle_id,
                manifest=_manifest(puzzle_id, raw["manifest"], author),
                solution=dict(raw["solution"]),
            )
        )
    return out


def _manifest(puzzle_id: str, body: dict, author: str | None) -> dict:
    """The entry's manifest block, with the fields every level shares filled in

    `id` is the entry's own key rather than a field anyone can get wrong, and
    it is the one thing here that is not carried through: a manifest whose id
    disagreed with its directory is precisely the failure this removes.
    """
    merged = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "id": puzzle_id,
        **{k: v for k, v in body.items() if k != "id"},
    }
    if author is not None:
        merged.setdefault("author", author)
    ordered = {k: merged[k] for k in _MANIFEST_ORDER if k in merged}
    ordered.update({k: v for k, v in merged.items() if k not in ordered})
    return ordered


def _serialise(data: dict) -> str:
    """The on-disk spelling. Matches what the puzzle directories already held:
    two-space indent, a trailing newline, and non-ASCII left as itself -- the
    backstories contain em dashes, and `\\u2014` in a file an author is meant
    to read is not an improvement."""
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


@dataclass(frozen=True)
class SyncResult:
    """What one `sync` did, or would do. `written` is empty for a clean check."""

    written: list[Path]
    checked: list[Path]

    @property
    def clean(self) -> bool:
        return not self.written


def sync(puzzles_dir: Path, *, check: bool = False) -> SyncResult:
    """Write every level's `manifest.json` and `solution.json` from the catalog

    With `check`, writes nothing and reports which files differ -- what CI and
    `tests/test_catalog.py` run, so that editing a generated file (or the
    catalog, without re-syncing) is a failure rather than a change that
    disappears at the next sync.

    A file is only rewritten when its content actually changes, so a no-op
    sync does not churn mtimes.
    """
    written: list[Path] = []
    checked: list[Path] = []
    for entry in load(puzzles_dir):
        directory = puzzles_dir / entry.id
        if not directory.is_dir():
            raise CatalogError(f"{puzzles_dir / CATALOG}: {entry.id} has no directory")
        for name, data in ((MANIFEST, entry.manifest), (SOLUTION, entry.solution)):
            path = directory / name
            checked.append(path)
            text = _serialise(data)
            if path.exists() and path.read_text() == text:
                continue
            written.append(path)
            if not check:
                path.write_text(text)
    return SyncResult(written=written, checked=checked)


def undeclared(puzzles_dir: Path) -> list[str]:
    """Puzzle directories the catalog does not describe.

    A directory with a `design.gds` and no catalog entry is a level whose
    prose is unreachable from the one file that is supposed to hold all of it
    -- which is the exact situation this module exists to end, so it is
    reported rather than ignored.
    """
    declared = {entry.id for entry in load(puzzles_dir)}
    found = [
        d.name
        for d in sorted(puzzles_dir.iterdir())
        if d.is_dir() and (d / "design.gds").is_file()
    ]
    return [name for name in found if name not in declared]