"""Verilog definitions for the generic primitives, generated from functions.py"""

from __future__ import annotations
from itertools import product

from .functions import COMBINATIONAL, SEQUENTIAL, CellFunction, FlopFunction


def _minterms(fn: CellFunction) -> str:
    terms = []
    for combo in product((0, 1), repeat=len(fn.inputs)):
        values = dict(zip(fn.inputs, combo))
        if fn.evaluate(values):
            terms.append(
                "("
                + " & ".join(f"{'' if v else '~'}{p}" for p, v in values.items())
                + ")"
            )
    if not terms:
        return "1'b0"
    if len(terms) == 1 << len(fn.inputs):
        return "1'b1"
    return " | ".join(terms)


def _combinational_module(name: str, fn: CellFunction) -> str:
    ports = ", ".join(fn.inputs)
    return (
        f"module {name} ({ports}, {fn.output});\n"
        f"  input {ports};\n"
        f"  output {fn.output};\n"
        f"  assign {fn.output} = {_minterms(fn)};\n"
        f"endmodule\n"
    )


def _flop_module(name: str, fn: FlopFunction) -> str:
    ports = [fn.clock, fn.data, fn.output] + ([fn.reset_n] if fn.reset_n else [])
    lines = [f"module {name} ({', '.join(ports)});"]
    lines.append(
        f"  input {fn.clock}, {fn.data}" + (f", {fn.reset_n};" if fn.reset_n else ";")
    )
    lines.append(f"  output reg {fn.output};")
    if fn.reset_n:
        lines.append(f"  always @(posedge {fn.clock} or negedge {fn.reset_n})")
        lines.append(f"    if (!{fn.reset_n}) {fn.output} <= 1'b0;")
        lines.append(f"    else {fn.output} <= {fn.data};")
    else:
        lines.append(f"  always @(posedge {fn.clock}) {fn.output} <= {fn.data};")
    lines.append("endmodule\n")
    return "\n".join(lines)


def verilog(generics: set[str] | None = None) -> str:
    """Emit module definitions for the named generics (all of them by default)"""
    out = ["// generated by gdsx -- generic primitive library", ""]
    seen = set()
    for table, emit in (
        (COMBINATIONAL, _combinational_module),
        (SEQUENTIAL, _flop_module),
    ):
        for fn in table.values():
            if fn.generic in seen or (
                generics is not None and fn.generic not in generics
            ):
                continue
            seen.add(fn.generic)
            out.append(emit(fn.generic, fn))
    return "\n".join(out)
