"""Verilog definitions for the generic primitives. Generated from Liberty"""

from __future__ import annotations

from .functions import generic_name
from .liberty import Cell, library, to_verilog


def _edge(expr, helpers: list[str], role: str) -> str:
    """Verilog edge spec for a Liberty condition.

    An edge list may only name a signal, so `!RESET_B` becomes `negedge RESET_B`
    and anything more involved (a gated or derived clock) gets its own wire.
    """
    if expr[0] == "var":
        return f"posedge {expr[1]}"
    if expr[0] == "not" and expr[1][0] == "var":
        return f"negedge {expr[1][1]}"
    helpers.append(f"  wire _{role} = {to_verilog(expr)};")
    return f"posedge _{role}"


def _sequential_body(cell: Cell) -> list[str]:
    seq = cell.sequential
    state = seq.state_var
    helpers: list[str] = []
    lines = [f"  reg {state};"]
    if len(seq.state_vars) > 1:
        lines.append(f"  wire {seq.state_vars[1]} = ~{state};")

    guards = []
    edges = [] if seq.is_latch else [_edge(seq.clocked_on, helpers, "clk")]
    if seq.clear is not None:
        edges.append(_edge(seq.clear, helpers, "clr"))
        guards.append((to_verilog(seq.clear), "1'b0"))
    if seq.preset is not None:
        edges.append(_edge(seq.preset, helpers, "set"))
        guards.append((to_verilog(seq.preset), "1'b1"))

    if seq.is_latch:
        lines.append("  always @(*)")
        for i, (condition, value) in enumerate(guards):
            lines.append(
                f"    {'if' if i == 0 else 'else if'} ({condition}) {state} <= {value};"
            )
        prefix = "    else if" if guards else "    if"
        lines.append(
            f"{prefix} ({to_verilog(seq.clocked_on)}) {state} <= {to_verilog(seq.next_state)};"
        )
    else:
        lines.append(f"  always @({' or '.join(edges)})")
        for i, (condition, value) in enumerate(guards):
            lines.append(
                f"    {'if' if i == 0 else 'else if'} ({condition}) {state} <= {value};"
            )
        prefix = "    else " if guards else "    "
        lines.append(f"{prefix}{state} <= {to_verilog(seq.next_state)};")
    return helpers + lines


def module(name: str, cell: Cell) -> str:
    ports = list(cell.inputs) + list(cell.outputs)
    lines = [f"module {name} ({', '.join(ports)});"]
    if cell.inputs:
        lines.append(f"  input {', '.join(cell.inputs)};")
    lines.append(f"  output {', '.join(cell.outputs)};")
    if cell.is_sequential:
        lines += _sequential_body(cell)
    for pin, expr in sorted(cell.functions.items()):
        lines.append(f"  assign {pin} = {to_verilog(expr)};")
    lines.append("endmodule\n")
    return "\n".join(lines)


def verilog(generics: set[str] | None = None) -> str:
    """Emit module definitions for the named generics (all of them by default)"""
    out = ["// generated by gdsx -- generic primitive library", ""]
    seen: dict[str, Cell] = {}
    for base, cell in sorted(library().items()):
        if not cell.has_behaviour:
            continue
        name = generic_name(base)
        if generics is not None and name not in generics:
            continue
        if name in seen:
            continue
        seen[name] = cell
        out.append(module(name, cell))
    return "\n".join(out)
