"""The hand-written cell functions. kept as test data to test the next implementation against"""

HAND_WRITTEN = {
    "and2": (("A", "B"), "X", lambda a, b: a & b),
    "and3": (("A", "B", "C"), "X", lambda a, b, c: a & b & c),
    "and4": (("A", "B", "C", "D"), "X", lambda a, b, c, d: a & b & c & d),
    "and4bb": (
        ("A_N", "B_N", "C", "D"),
        "X",
        lambda a, b, c, d: (1 - a) & (1 - b) & c & d,
    ),
    "or2": (("A", "B"), "X", lambda a, b: a | b),
    "or3": (("A", "B", "C"), "X", lambda a, b, c: a | b | c),
    "nand2": (("A", "B"), "Y", lambda a, b: 1 - (a & b)),
    "nand3": (("A", "B", "C"), "Y", lambda a, b, c: 1 - (a & b & c)),
    "nor2": (("A", "B"), "Y", lambda a, b: 1 - (a | b)),
    "nor3": (("A", "B", "C"), "Y", lambda a, b, c: 1 - (a | b | c)),
    "xor2": (("A", "B"), "X", lambda a, b: a ^ b),
    "xnor2": (("A", "B"), "Y", lambda a, b: 1 - (a ^ b)),
    "inv": (("A",), "Y", lambda a: 1 - a),
    "buf": (("A",), "X", lambda a: a),
    "clkbuf": (("A",), "X", lambda a: a),
    "clkinv": (("A",), "Y", lambda a: 1 - a),
    "mux2": (("A0", "A1", "S"), "X", lambda a0, a1, s: a1 if s else a0),
    "mux2i": (("A0", "A1", "S"), "Y", lambda a0, a1, s: 1 - (a1 if s else a0)),
    "a21o": (("A1", "A2", "B1"), "X", lambda a1, a2, b1: (a1 & a2) | b1),
    "a21oi": (("A1", "A2", "B1"), "Y", lambda a1, a2, b1: 1 - ((a1 & a2) | b1)),
    "a21bo": (("A1", "A2", "B1_N"), "X", lambda a1, a2, b: (a1 & a2) | (1 - b)),
    "a21boi": (("A1", "A2", "B1_N"), "Y", lambda a1, a2, b: 1 - ((a1 & a2) | (1 - b))),
    "a31o": (("A1", "A2", "A3", "B1"), "X", lambda a1, a2, a3, b1: (a1 & a2 & a3) | b1),
    "a31oi": (
        ("A1", "A2", "A3", "B1"),
        "Y",
        lambda a1, a2, a3, b1: 1 - ((a1 & a2 & a3) | b1),
    ),
    "a22o": (
        ("A1", "A2", "B1", "B2"),
        "X",
        lambda a1, a2, b1, b2: (a1 & a2) | (b1 & b2),
    ),
    "a22oi": (
        ("A1", "A2", "B1", "B2"),
        "Y",
        lambda a1, a2, b1, b2: 1 - ((a1 & a2) | (b1 & b2)),
    ),
    "o21a": (("A1", "A2", "B1"), "X", lambda a1, a2, b1: (a1 | a2) & b1),
    "o21ai": (("A1", "A2", "B1"), "Y", lambda a1, a2, b1: 1 - ((a1 | a2) & b1)),
    "o21bai": (("A1", "A2", "B1_N"), "Y", lambda a1, a2, b: 1 - ((a1 | a2) & (1 - b))),
    "o31ai": (
        ("A1", "A2", "A3", "B1"),
        "Y",
        lambda a1, a2, a3, b1: 1 - ((a1 | a2 | a3) & b1),
    ),
    "o22ai": (
        ("A1", "A2", "B1", "B2"),
        "Y",
        lambda a1, a2, b1, b2: 1 - ((a1 | a2) & (b1 | b2)),
    ),
}
